import { getPages } from "@/sanity/sanity-utils";
import "../globals.css";
import Link from "next/link";

export const metadata = {
  title: "My Blog",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pages = await getPages();
  return (
    <html lang="en">
      <body className="max-w-3xl mx-auto py-20">
        <header className="flex items-center justify-between">
          <Link
            className="bg-gradient-to-r from-orange-400 via-red-500 to-purple-500 bg-clip-text text-transparent text-lg font-bold"
            href={"/"}
          >
            Blog
          </Link>
          <div className="flex items-center gap-5 text-sm text-gray-600">
            {pages.map((page) => (
              <Link
                key={page._id}
                href={`/${page.slug}`}
                className="hover:underline"
              >
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        <main className="py-20">{children}</main>
      </body>
    </html>
  );
}
